import type { Metadata } from "next";
import { Poppins } from "next/font/google";  // Import the Poppins font
import "./globals.css";

// Initialize Poppins font with optimization options
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],  // You can specify the weights you need
  subsets: ["latin"],  // Specify the character subset (you can also add others like 'latin-ext')
  display: "swap",  // This ensures smooth font loading
  variable: "--font-poppins",  // This will allow you to use the font in the body
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
